import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  PDFViewer,
  Font,
  Image,
} from "@react-pdf/renderer";
import reportStyles from "./reportStyles";
import ttf from "../../../assets/NotoSansSC-Regular.ttf";
import ttfb from "../../../assets/NotoSansSC-Bold.ttf";
import PDFloading from "./PDFloading";
import shipImage from "../../../assets/images/PDFgenShip.png";
import tableDecoSvg from "../../../assets/images/PDFtableImage.png";

Font.register({
  family: "NotoSansSC",
  src: ttf,
});

Font.register({
  family: "NotoSansSC-Bold",
  src: ttfb,
});

const styles = StyleSheet.create(reportStyles);

const formatDate = (dateString) => {
  const date = new Date(dateString);
  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  const month = monthNames[date.getMonth()];
  const year = date.getFullYear();
  return `${month} ${year}`;
};

export default function PDFgen({
  shipData,
  images = {},
  isCapturing = false,
  hasImages = false,
  uploadedShipImage = null,
}) {
  if (isCapturing || !hasImages) {
    return <PDFloading />;
  }

  const MyDocument = () => (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page} wrap={false}>
        <View style={styles.contentArea}>
          {/* Section 1 - Title */}
          <View style={styles.section1}>
            <View style={styles.section1HeaderContainer}>
              <View style={styles.redCapsule}>
                <Text style={styles.redCapsuleText}>
                  {shipData.loadProfile.shipType}
                </Text>
              </View>
              <Text style={styles.dateText}>
                {formatDate(shipData.updatedAt)}
              </Text>
            </View>

            <Text style={styles.page1Title}>{shipData.name}</Text>
            <Text style={styles.page1GreyText}>Ship Analysis Report</Text>
            <Text style={styles.page1DescriptionText}>
              Generated by: AzurE e-ship calculator
            </Text>
          </View>
          {uploadedShipImage && (
            <View style={styles.shipImageDisplay}>
              <Image src={uploadedShipImage} style={styles.displayImage} />
            </View>
          )}

          {/* Section 2 - Ship Info */}
          <View style={styles.section2}>
            <Text style={styles.secondaryTitle}>
              Introduction of Ship {shipData.name}
            </Text>
            <Text style={styles.descriptionText}>
              {shipData.reportCenter?.introduction}
            </Text>
          </View>

          {/* Section 3 - Tables with headers at bottom */}
          <View style={styles.section3}>
            <Text style={styles.secondaryTitle}>Vessel Specifications</Text>
            <View style={styles.tablesContainer}>
              <View style={styles.tableRow}>
                {/* Dimensions Table */}
                <View style={styles.table}>
                  <View style={styles.tableContent}>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>LOA</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.loa} m
                      </Text>
                    </View>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>LWL</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.lwl} m
                      </Text>
                    </View>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>Draft</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.draft} m
                      </Text>
                    </View>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>Depth</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.depth} m
                      </Text>
                    </View>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>B max</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.bmax} m
                      </Text>
                    </View>
                    <View style={styles.tableDataRowLast}>
                      <Text style={styles.tableLabel}>Displacement</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.displacement} Tons
                      </Text>
                    </View>
                  </View>
                  {/* Header moved to bottom */}
                  <View style={styles.tableTitleContainer}>
                    <Image src={tableDecoSvg} style={styles.tableArrowDeco} />
                    <Text style={styles.tableTitle}>Dimensions</Text>
                  </View>
                </View>

                {/* Performance Table */}
                <View style={styles.table}>
                  <View style={styles.tableContent}>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>Cruise Speed</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.cruiseSpeed} Knots
                      </Text>
                    </View>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>Max Speed</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.maxSpeed} Knots
                      </Text>
                    </View>
                    <View style={styles.tableDataRow}>
                      <Text style={styles.tableLabel}>Crew</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.crew} People
                      </Text>
                    </View>
                    <View style={styles.tableDataRowLast}>
                      <Text style={styles.tableLabel}>Cruise Range</Text>
                      <Text style={styles.tableValue}>
                        {shipData.reportCenter?.cruiseRange} nms
                      </Text>
                    </View>
                  </View>
                  {/* Header moved to bottom */}
                  <View style={styles.tableTitleContainer}>
                    <Image src={tableDecoSvg} style={styles.tableArrowDeco} />
                    <Text style={styles.tableTitle}>Performance</Text>
                  </View>
                </View>
              </View>
            </View>
          </View>

          {/* Additional Images Section */}
          {images.singleLineDiagram && (
            <View style={styles.section5}>
              <Text style={styles.secondaryTitle}>Single Line Diagram</Text>
              <Image
                src={images.singleLineDiagram}
                style={styles.displayImage}
              />
            </View>
          )}

          {images.biddingList && (
            <View style={styles.section6}>
              <Text style={styles.secondaryTitle}>Equipment List</Text>
              <Image src={images.biddingList} style={styles.displayImage} />
            </View>
          )}

          {images.costAnalysis && (
            <View style={styles.section7}>
              <Text style={styles.secondaryTitle}>Cost Analysis</Text>
              <Image src={images.costAnalysis} style={styles.displayImage} />
            </View>
          )}

          {images.workingConditionTables && images.energyConsumptionGraph && (
            <View style={styles.section8}>
              <Text style={styles.secondaryTitle}>Working Condition</Text>
              {images.workingConditionTables.map((tableImage, index) => (
                <View key={`working-condition-${index}`}>
                  <Image src={tableImage} style={styles.displayImage} />
                </View>
              ))}
              <Image
                src={images.energyConsumptionGraph}
                style={styles.displayImage}
              />
            </View>
          )}

          <View style={styles.section9}>
            <View style={styles.textArea}>
              <Text style={styles.disclaimerText}>
                <Text style={styles.disclaimerBold}>Note: </Text>
                The AzurE E-ship software and its accompanying documentation are
                provided by General Energies Electric Ship Technology (Shanghai)
                Co., Ltd. “as is,” without any express or implied warranties
                regarding suitability, accuracy, completeness, or fitness for a
                particular purpose. Any design, calculation, or decision results
                generated through the use of this software are for reference
                only and should not be considered as the sole basis for action.
                General Energies Electric Ship Technology (Shanghai) Co., Ltd.
                and its partners shall not be liable for any direct, indirect,
                incidental, or consequential damages, including but not limited
                to loss of profits, business interruption, or data loss, arising
                from the use or inability to use this software. Users should
                operate the software with relevant professional knowledge and
                experience and shall be solely responsible for their use and
                results.
              </Text>
            </View>
          </View>
        </View>
      </Page>
    </Document>
  );

  return (
    <PDFViewer width="100%" height="100%">
      <MyDocument />
    </PDFViewer>
  );
}
